---
- name: Configure Docker on Deploy Server
  hosts: all
  become: true
  tasks:
    - name: Update apt repositories
      command: apt update

    - name: Install Python and pip
      command: apt install -y python3-pip

    - name: Install Docker
      command: apt-get install -y docker.io

    - name: Start Docker service
      command: systemctl start docker

    - name: Remove existing Medicure container (if any)
      command: >
        docker rm -f $(docker ps -aq --filter "ancestor=pradeep781/medicure:1.0")
      ignore_errors: yes

    - name: Run new Docker container for Medicure
      command: docker run -itd -p 8084:8082 pradeep781/medicure:1.0
