- name: Configure Docker and deploy Medicure container
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      command: sudo apt update

    - name: Install Python3-pip
      command: sudo apt install -y python3-pip

    - name: Install Docker
      command: sudo apt-get install -y docker.io

    - name: Start Docker service
      command: sudo systemctl start docker

    - name: Deploy Medicure container from Docker Hub
      command: docker run -itd -p 8084:8082 pradeep781/medicure:1.0
