- name: Configure Docker on EC2 Instances for Healthcare Project
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Remove containerd.io to resolve conflicts
      command: sudo apt-get remove -y containerd.io
      ignore_errors: yes  # In case it's not installed, continue without failing

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Medicure Docker container
      command: docker run -itd -p 8085:8082 pradeep781/medicure:1.0
